SiteConfig:
  extensions:
    - 'SiteConfigExtension'
Page_Controller:
  extensions:
    - 'Page_ControllerExtension'
Image:
  extensions:
    - 'ImageExtension'
ProjectPage:
  extensions:
    - 'FigureExtension'
BlogPost:
  extensions:
    - 'FigureExtension'